### ISSUE TITLE
GIL safety?

### ISSUE THREAD

**Issue by bo-at-pleno** [tanghaibao/pybind11_log#2]
Hello, thank you submitting this as an open source library! I came across the same problem and your repo showed up in the google search.

do you know what would happen if the C++ method exposed via pybind releases the GIL, would logging still work in this case? 

Thanks!

**Comment by nradtke** [comment]
I know this is a bit old, but based on what I'm seeing in my usage, it will not work.  I had a C++ method that spun off a long-lived thread (outside the GIL) and got this when I tried to call logging in it:

`pybind11::handle::inc_ref() is being called while the GIL is either not held or invalid. Please see https://pybind11.readthedocs.io/en/stable/advanced/misc.html#common-sources-of-global-interpreter-lock-errors for debugging advice.
If you are convinced there is no bug in your code, you can #define PYBIND11_NO_ASSERT_GIL_HELD_INCREF_DECREF to disable this check. In that case you have to ensure this #define is consistently used for all translation units linked into a given pybind11 extension, otherwise there will be ODR violations. The failing pybind11::handle::inc_ref() call was triggered on a NoneType object.
[*** LOG ERROR #0001 ***] [2024-10-17 11:35:01] [pybind11_log] pybind11::handle::inc_ref() PyGILState_Check() failure.`

**Comment by tanghaibao** [comment]
thanks for reporting this, I'll look into it but not yet obvious what the solution may be

**Comment by tanghaibao** [comment]
@nradtke 

The code would now acquire the GIL during logging. I also added a `threaded_log()` example. There are `init_mt()` and `init_st()`, for multi-threaded and single-threaded logger.

**Comment by nradtke** [comment]
I integrated the new version into my codebase and it appears to now work as hoped.  I'd consider this issue fixed!
